### ISSUE TITLE
"Mud" conflicting recipe with BiomesOP

### ISSUE THREAD

**Issue by ghost** [capnkirok/animaniamod#312] opened 2019-05-02 16:35 UTC
- [x] Biomes O' Plenty is updated to the latest available version.
- [x] Animania is updated to the latest available version.
- [x] This issue occurs with Minecraft 1.12.2

- [x] Forge is updated to the latest available version.
- [x] This issue occurs *WITHOUT* Optifine, Sponge or similar mods installed.
- [x] This issue can be reproduced with only BOP + Animania on their own.

- [x] All other mods which appear to be involved are updated to their latest versions.

#### Issue Description:
"Mud" is a large part of the [Animania](https://minecraft.curseforge.com/projects/animania) mod. The "Mud" allows pigs to stay happy and keep them entertained- without it, they may become unhappy.

The issue is the recipe conflict between them. This can be easily fixed.

#### Steps to reproduce:

1. Water Bucket + Dirt = Mud

____
#### Affected Versions

- Biomes O' Plenty: BiomesOPlenty-1.12.2-7.0.1.2427-universal.jar
- Animania: Animania-1.12.2-1.6.2
- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.5.2836

**Comment by katubug** [comment] 2019-06-06 03:30
I can confirm this is the case. I have edited the recipe using CraftTweaker, but not everyone will be willing or able to do that.

Edit: If anyone is motivated enough to fix this on their own, here is the script:

```
import crafttweaker.item.IIngredient;
import crafttweaker.item.IItemStack;
import crafttweaker.oredict.IOreDict;
import crafttweaker.oredict.IOreDictEntry;

//Removes Biomes O Plenty's Mud recipe in favor of Animania's (but retains mud ball > block recipe)
recipes.remove(<biomesoplenty:mud>);
recipes.addShapeless(<biomesoplenty:mud>, [<ore:ballMud>, <biomesoplenty:mudball>, <ore:ballMud>, <ore:ballMud>]);
```

Requires Crafttweaker. Simply make a file with the .zs extension and place it in the "/scripts/" directory (make one if you don't have one), then paste the above into it.

**Comment by Deshiba** [comment] 2019-06-07 07:36
I don't exactly see the problem. Even if there is a crafting recipe conflict, the pigs have been made to accept the BOP mud all the same. So even if you get the BOP version of mud, then it's still functional.

Unless you're getting other issues?

**Comment by ghost** [comment] 2019-06-07 14:56
I don’t think the BOP mud is functional with Animania. As with BOP mud they seem unhappy and die (I have the config option set to animals able to die)

But with Animania Mud in the same relative area it appears that they seem happier than they do with BOP mud. 

This could just be me, I haven’t thoroughly tested it but I’ve reported this an issue so the dev is aware.

**Comment by ghost** [comment] 2019-06-07 14:57
Regardless, the issue was opened to notify the developer that his mud is conflicting.

**Comment by MizuNomy** [comment] 2019-06-17 01:01
I think the latest BOP and Animania mud is not compatible at all. I am pretty sure about that.

**Comment by Tschipp** [comment] 2019-08-21 14:47
@eviqnn happiness isn't a factor that decides if an animal dies or not, it's only food and water. So your animals probably died due to hunger and thirst. But the recipe can still be adjusted.

**Comment by ghost** [comment] 2019-08-21 15:21
@Tschipp
They are dying due to unhappiness. Check the configuration. It will “display particles if animals are unhappy”

As I said. This is mainly a compat report to let people aware.

**Comment by Tschipp** [comment] 2019-08-21 15:27
```java
if (!fed && !watered)
{
	this.addPotionEffect(new PotionEffect(MobEffects.WEAKNESS, 2, 1, false, false));
	if (AnimaniaConfig.gameRules.animalsStarve)
	{
	              if (this.damageTimer >= AnimaniaConfig.careAndFeeding.starvationTimer)
	              {
				this.attackEntityFrom(DamageSource.STARVE, 4f);
				this.damageTimer = 0;
			}
		        this.damageTimer++;
	}
}
```

This is the code that controls animals dying. It only checks for food and water.

**Comment by ghost** [comment] 2019-08-21 16:09
Maybe consider changing the configuration file to say “display particles when an animal is hungry/thirsty”

I’m not trying to be an ass; I’m just forwarding suggestions. I assumed that the particles were due to unhappiness. Not feed or water.

**Comment by Tschipp** [comment] 2019-08-21 16:13
Yeah, that seems fair

**Comment by capnkirok** [comment] 2019-08-24 12:25
@eviqnn Ok, the update to the config label will be in next release

**Comment by capnkirok** [comment] 2019-08-24 12:34
Also, I've changed the recipe so that 2 dirt + 1 water bucket = 4 mud blocks. In the next release.

**Closed as completed** 2019-09-15 08:54 UTC
Labels: 1.12, compat, added in next release
