### ISSUE TITLE
Crash when feeding Hedgehog with PotionCore installed

### ISSUE THREAD

**Issue by Luke616** [capnkirok/animaniamod#221] opened 2018-11-18 19:07 UTC
### Expected Behavior
The game would not crash when a hedgehog was fed

### Actual Behavior
https://paste.dimdev.org/oyaliwajud.mccrash

### Steps to Reproduce
Feed a hedgehog with PotionCore installed. I haven't had a chance to strip down mods from my pack to make sure its specifically PotionCore that's causing issues, but judging from the crash log it seems to be some sort of error between PotionCore and Animania

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
forge-14.23.5.2775
animania-1.12.2-1.6.1
PotionCore-1.6_for_1.12.2

Thanks!

**Comment by Tschipp** [comment] 2018-11-19 16:11
Duplicate of #219

**Closed as completed by Tschipp** 2018-11-19 16:11 UTC
Labels: bug, duplicate
