### ISSUE TITLE
[Bug] Version Check

### ISSUE THREAD

**Issue by Zarpyk** [capnkirok/animaniamod#485] opened 2021-01-12 16:40 UTC
### Expected Behavior
The mod detect 2.0.0.23 as newest version and I have 2.0.2.26

### Actual Behavior
Detect 2.0.2.26 as newest version

### Steps to Reproduce
Join to the world

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, 2.0.2.26, Single Player

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/30746531/104344298-4372fb00-54fd-11eb-878d-573be53620f4.png)
![image](https://user-images.githubusercontent.com/30746531/104344332-4ec62680-54fd-11eb-8a46-59a524087afd.png)

**Comment by RyanCR3000** [comment] 2021-01-14 07:19
**Expected Behavior**

Normal world loading (server)
No crashes

**Steps to Reproduce**
Spawn some Sheep entity (uknown)

Join to the world
Version of Minecraft 1.12.2, Server
Error type: instant crash Client side
Server seems to be fine.
Help please?

(no screenshot available at this time)

**Comment by axalox** [comment] 2021-05-18 06:51
Hello

I like your mod

I have the same error for upgrading my version

I use 
![image](https://user-images.githubusercontent.com/32990916/118605165-4422e300-b7b6-11eb-8241-2544853a0d3d.png)

**Comment by LulzRose** [comment] 2021-06-08 23:45
Can confirm that when a new world is joined it specifies to download 2.0.0.23 with the newest release.

**Comment by Tschipp** [comment] 2021-06-10 11:18
fixed now

**Closed as completed by Tschipp** 2021-06-10 11:18 UTC
Labels: bug, 1.12
