### ISSUE TITLE
Crash While Travelling In World In Spectator Mode (/gamemode 3)

### ISSUE THREAD

**Issue by KenyMylankca** [capnkirok/animaniamod#178] opened 2018-10-21 09:34 UTC
it just crashed while im travelling in my world in single player in gamemode 3. **it crashed when i switch to gamemode 1**(creative mode)(after i enter command _/gamemode 3_ while in blocks).
[crash-2018-10-21_12.32.24-server.txt](https://github.com/capnkirok/animaniamod/files/2499014/crash-2018-10-21_12.32.24-server.txt)

animania: 1.5.1.1 (mc 1.12.2)
edit: i was in walls(blocks) when switch to creative mode)

**Comment by Tschipp** [comment] 2018-10-21 10:02
I'm pretty sure this is a duplicate of #93, and thus fixed in the next release

**Closed as completed by Tschipp** 2018-10-21 10:02 UTC
Labels: duplicate
