### ISSUE TITLE
Trough's Don't Work at All

### ISSUE THREAD

**Issue by Sirfancytoad** [capnkirok/animaniamod#327] opened 2019-07-05 16:21 UTC
### Expected Behavior
Animals will go up to the trough if they are hungry (or thirsty) and drink or eat from said trough.

### Actual Behavior
Animals will either not go to the trough at all when they are hungry or thirsty, or the animal will get stuck in the trough and other animals will not be able to eat or drink from that trough. 

### Steps to Reproduce
place a trough with multiple animals around and place water or food into the trough and wait until the animals become hungry or thirsty.

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, Single Player

**Comment by capnkirok** [comment] 2019-07-10 14:03
Well, they work for some animals. The problem is with hitboxes vs. the Minecraft loc grid. An adjustment was made some time ago and now the default move AI in Minecraft thinks the animals are close to the trough, but the AI does not. 

We need to make the drink/eat AI more forgiving.

**Comment by Sirfancytoad** [comment] 2019-07-10 14:49
Okay, is there any easy way to fix this? Or any plans to fix it? I don’t want to sound ungrateful for the mod (sorry if I come off that way) I would just love to implement this into my single player modded survival.

**Comment by capnkirok** [comment] 2019-07-10 15:08
Well, it's not easy, but it needs to be fixed in the code. I've added to our bug list, and have started working on our rather long list of bugs. No ETA, but it's being worked on :)

**Comment by Sirfancytoad** [comment] 2019-07-10 15:32
Yay!! So glad to know that it’s known and is being checked in on. Thank you for the response and good luck :)

**Comment by capnkirok** [comment] 2019-08-25 22:14
I was able to replicate the issue, and then was able to adjust the AI so it's more forgiving with proximity. Tested with numerous animals and looks good. Will be in next release.

**Comment by Sirfancytoad** [comment] 2019-08-25 22:19
Glad to hear that. Thanks for the update! Love the mod, keep up the great work!

**Closed as completed** 2019-09-15 08:54 UTC
Labels: bug, 1.12, fixed in next release, AI
