### ISSUE TITLE
Animania not working???

### ISSUE THREAD

**Issue by raquelsanz100** [capnkirok/animaniamod#400] opened 2020-03-03 18:54 UTC
So I created a private server with some other mods to play with my boyfriend. I really like this mod so I wanted to add it to the server; however when I get into the server, all our cows, pigs and the rest of animals are exactly the same; I've walked around to see if I spot any new pigs or cows or something, but everything is exactly the same as if I hadn't installed the mod. The mod is indeed installed because I can see it in the Mods options and I can edit its configuration; but it is not playable and I don't understand why. Hopefully someone can help me out. Thanks in advance.

**Comment by Tschipp** [comment] 2020-03-05 12:44
I am assuming you have the mod on the server as well. Vanilla animals (that are existing in the world) are no longer replaced by animania, so if you generated the world before adding animania, those vanilla animals will still be there.

**Comment by raquelsanz100** [comment] 2020-03-05 12:49
Ahh, really? So if we want the animals on the server we would have to make
a new one I assume? That sucks... 😞

**Comment by Princess22503** [comment] 2020-03-07 23:43
Just wondering, since an almost identical thing is happening to me, if we kill all of the vanilla animals, are animania animals supposed to spawn in? Because if so, after multiple /kill @e and waiting for new mobs to spawn in, vanilla mobs continue to spawn.

**Comment by AshyAspen** [comment] 2020-03-27 12:27
Same here, on Forge 1.12.2-14.23.5.2847 with mod version 1.12.2-1.7.3

I thought originally it was Biomes O Plenty biomes not registering as biomes for them to spawn, but it seems to have support from what I read on the mod page. I am on an old world so I did /kill @e[type=!player] and it killed a bunch of things but so far no Animania mobs have spawned yet, just vanilla mobs seemingly outside of the chunks where I did the command and very little or close to no passive mobs spawning near me in the chunks where they were killed at all. 

I also have the pregeneration mod so maybe because it pregenerated a bunch of chunks before the mod somehow the mob cap was his or something? but from what I thought the mob cap was regional on Java Edition.

Not sure quite what's happening. In the config "game rules" seems to have "replaceVanilla*insert-mob-here*" all set to true as default in my version so perhaps it's different than those above me? They didn't really say their versions so I have no idea.

**Comment by Tschipp** [comment] 2020-04-19 19:15
I'm closing this as it's been shown many times that animals *do* spawn.

**Closed as completed by Tschipp** 2020-04-19 19:15 UTC

**Comment by AshyAspen** [comment] 2020-04-20 11:28
Just to clarify, it’s been shown even on worlds that were already pregenerated without the mod? I think that was my only issue, it was an old world. New worlds had them. Unless you don’t intend to make it work on old worlds or it’s already been shown to work on old worlds, that’s fine too. Just sharing my report.

**Comment by Tschipp** [comment] 2020-04-20 20:37
Animania animals don't replace existing animals. We changed that a while ago. Also, as is normal with vanilla as well, generated chunks spawn new passive mobs less frequently (almost never) if the mobcap is filled, which it almost always is. So unless you're generating new chunks, this is expected behavior.

**Comment by AshyAspen** [comment] 2020-04-21 00:22
Got it. It’s a shame for old worlds, but since it doesn’t effect new worlds or other parts of the mod I understand why you wouldn’t want to delve be into some hacky fix that has to work around regular spawn mechanics. Thanks for the clarification!
