### ISSUE TITLE
Animals Stuck in Walls and Troughs/Don't Find Food or Water

### ISSUE THREAD

**Issue by BiNonJay** [capnkirok/animaniamod#421] opened 2020-05-01 17:20 UTC
### Expected Behavior
Animals should be not be able to phase into walls or troughs, and should be able to find food and water on their own

### Actual Behavior
Animals will sometimes phase into walls, get stuck, and die. Animals will often get stuck inside of their troughs and not be able to eat or drink. Animals still have trouble finding their own food and water.

### Steps to Reproduce
Create a farm. Use fencing and blocks to keep animals in. Add troughs of food and water. Let it all play itself out.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft Version 1.12.2
Animania Version 1.12.2-1.7.3

**Comment by Tschipp** [comment] 2020-05-03 10:02
Duplicate of #335 and many others.

**Closed as completed by Tschipp** 2020-05-03 10:02 UTC
Labels: duplicate
