### ISSUE TITLE
Botania Functional Flowers can be eaten by animals

### ISSUE THREAD

**Issue by DoomRater** [capnkirok/animaniamod#325] opened 2019-06-26 14:53 UTC
### Expected Behavior
Functional Flowers are special flowers that cost far more than regular flowers and should not taste good to animals.

### Actual Behavior
Animals will eat any and all Botania flowers, be they functional or aesthetic.

### Steps to Reproduce
Plant a Hopperhock to collect all them lovely feathers in your animal pen.  Wait a while for the cows to come by and eat it.  One perfectly good Rune of Air gone!

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, Animania 1.6.2, Botania r1.10-361

**Comment by MizuNomy** [comment] 2019-07-17 04:46
Consider separating them both. It's not a bug or any issue. It's animals nature.

**Comment by DoomRater** [comment] 2019-07-17 11:39
Or I can just disable the animania config where they eat flowers, because I'm not dealing with this behavior and neither are any of my players.

**Comment by DoomRater** [comment] 2019-07-17 12:45
Excuse me SuperPawmaple, you are not a developer of this mod.  It is not your place to say whether something is a bug or an issue.

**Comment by MizuNomy** [comment] 2019-07-18 11:16
> Excuse me SuperPawmaple, you are not a developer of this mod. It is not your place to say whether something is a bug or an issue.

I am just a Wiki helper for Animania mod trying to help :D

**Comment by capnkirok** [comment] 2019-08-19 00:48
@DoomRater Yes, right now, the Herbivore animals eat all Plants, with no way to blacklist. I can imagine the frustration of not fencing off your precious Botania flowers.

**Comment by katubug** [comment] 2019-08-26 19:46
Additionally, animals will eat anything grown on Agricraft's Crop Sticks, which destroys the crop sticks (which harvesting does not). To be able to blacklist those would be very helpful, because I like the default behavior, but in my pack I was hoping to have Crop Sticks be a way to protect crops from being eaten.

I hope it's all right that I'm piggybacking here instead of making a new issue - it seemed similar enough.

**Comment by Tschipp** [comment] 2020-09-11 14:19
I have given this some thought and I think I'm gonna close this as working as intended. It makes sense that animals eat your flowers and crops. You should make sure to separate them, as you also would in real life.

**Closed as completed by Tschipp** 2020-09-11 14:19 UTC
Labels: suggestion
