### ISSUE TITLE
[2 in One] Bug and Error

### ISSUE THREAD

**Issue by Feranogame** [capnkirok/animaniamod#229] opened 2018-11-25 18:34 UTC
### Expected Behavior
1: The game shouldn't detect a new version.
2: Peacock should be with capital letter.

### Actual Behavior
1: The game detects an old version as new.
2: One item has peacock with lowercase letter.

### Steps to Reproduce
1: Just start the game in a world.
2: Just check the name of the item.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, Animania: 1.12.2 1.6.2, Single Player

### Screenshots encouraged
1: https://gyazo.com/19aff9742c20e226b0fb803cebc90998
2: https://gyazo.com/b2d7bb7cadb48a799d89e1cb7e45028a

**Comment by Tschipp** [comment] 2018-11-25 20:28
1 is a duplicate of #228, fixed 2.

**Comment by capnkirok** [comment] 2018-11-27 04:47
1 is fixed

**Closed as completed** 2019-09-15 08:54 UTC
Labels: bug, fixed in next release
