### ISSUE TITLE
Pink/Purple Texture Glitch While on Horse

### ISSUE THREAD

**Issue by Rage-GitHub** [capnkirok/animaniamod#320] opened 2019-06-01 00:21 UTC
### Expected Behavior
Normal entry of the horse inventory without any texture glitches appearing.

### Actual Behavior
Weird pink/purple texture glitch appears while on the horse and the horse is tied up to a fence post with a lead.

### Steps to Reproduce

1. Get yourself a lead and a Stallion.
2. Tie the Stallion up to a fence post with the lead.
3. Ride the horse and open the inventory.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2 / Animania 1.6.2 / Singleplayer

### Screenshots encouraged
![unknown](https://user-images.githubusercontent.com/17907584/58740919-a031a880-83e1-11e9-83c0-b44caea6b171.png)

**Comment by MizuNomy** [comment] 2019-06-17 00:41
Hello. Are you using the latest forge launcher? I have had this problem when JEI was updating! Making sure using the latest mods and forge ! Hope that solve your issue!

**Comment by capnkirok** [comment] 2019-08-20 00:07
Not reproducible. Any other mods/shaders you are using?

![image](https://user-images.githubusercontent.com/9628379/63307614-016c6800-c2bd-11e9-8929-c43c125dee07.png)

**Comment by Tschipp** [comment] 2019-08-20 08:17
Yeah no I don't think this is us, seems you have a ton of other mods installed.

**Comment by Tschipp** [comment] 2019-08-20 09:07
Also, this seems to be optifine/shader related. Closing this.

**Closed as completed by Tschipp** 2019-08-20 09:07 UTC
Labels: 1.12, Can't Reproduce 🤔
