### ISSUE TITLE
[Crash] When Joining vanilla servers

### ISSUE THREAD

**Issue by SheroxGG** [capnkirok/animaniamod#426] opened 2020-05-27 16:28 UTC
### Expected Behavior
Join a vanilla server with the mod installed 

### Actual Behavior
When joining a vanilla server minecraft crashes

### Steps to Reproduce
Have Animania installed, joining a server with the same minecraft version.

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2 1.7.3

### Crash log, latest.log
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  CreativePatchingLoader (CreativeCore_v1.10.13_mc1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 5/27/20 6:20 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.animania.common.handler.ItemHandler.regItemEggColors(ItemHandler.java:298)
	at com.animania.common.events.EntityEventHandler.onEntityJoinWorld(EntityEventHandler.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_319_EntityEventHandler_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72897_h(World.java:3552)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1820)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.animania.common.handler.ItemHandler.regItemEggColors(ItemHandler.java:298)
	at com.animania.common.events.EntityEventHandler.onEntityJoinWorld(EntityEventHandler.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_319_EntityEventHandler_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72897_h(World.java:3552)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['SheroxGG'/81, l='MpServer', x=3.27, y=63.50, z=-9.56]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (1,62,1), Chunk: (at 1,3,1 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3415644 game time, 7185000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 113 total; [EntitySkeleton['Skeleton'/47104, l='MpServer', x=-45.27, y=97.00, z=51.48], EntityCow['Cow'/2, l='MpServer', x=-69.17, y=100.00, z=-67.45], EntityCreeper['Creeper'/38914, l='MpServer', x=-37.50, y=89.00, z=-45.50], EntitySkeleton['Skeleton'/47107, l='MpServer', x=-33.50, y=95.00, z=45.50], EntityChicken['Chicken'/9, l='MpServer', x=-65.48, y=93.50, z=33.13], EntityChicken['Chicken'/11, l='MpServer', x=-52.80, y=58.00, z=-69.20], EntityZombie['Zombie'/41739, l='MpServer', x=38.50, y=95.00, z=-39.50], EntityCreeper['Creeper'/46349, l='MpServer', x=64.47, y=84.00, z=69.21], EntitySheep['Sheep'/29, l='MpServer', x=-40.50, y=58.00, z=-88.50], EntitySheep['Sheep'/32, l='MpServer', x=-38.55, y=93.50, z=-24.55], EntityChicken['Chicken'/33, l='MpServer', x=-42.80, y=93.50, z=26.80], EntityBat['Bat'/43298, l='MpServer', x=43.45, y=60.60, z=65.42], EntityCreeper['Creeper'/38693, l='MpServer', x=62.50, y=75.00, z=-9.50], EntityChicken['Chicken'/41, l='MpServer', x=-22.80, y=93.00, z=54.20], EntityPig['Pig'/45, l='MpServer', x=-10.28, y=82.00, z=-87.47], EntityZombie['Zombie'/46134, l='MpServer', x=61.50, y=79.00, z=4.50], EntityZombie['Zombie'/37175, l='MpServer', x=41.50, y=95.00, z=37.50], EntityCreeper['Creeper'/44098, l='MpServer', x=-40.50, y=99.00, z=55.50], EntityCreeper['Creeper'/44100, l='MpServer', x=-40.50, y=99.00, z=54.50], EntityCreeper['Creeper'/44101, l='MpServer', x=-37.50, y=99.00, z=57.50], EntitySheep['Sheep'/74, l='MpServer', x=39.55, y=93.50, z=-25.55], EntityPig['Pig'/37200, l='MpServer', x=-64.50, y=100.00, z=38.50], EntityPig['Pig'/37201, l='MpServer', x=-63.50, y=100.00, z=41.50], EntityCow['Cow'/37203, l='MpServer', x=-61.50, y=100.00, z=31.45], EntityCow['Cow'/37204, l='MpServer', x=-61.50, y=100.00, z=32.57], EntityChicken['Chicken'/84, l='MpServer', x=59.08, y=79.00, z=24.50], EntityChicken['Chicken'/91, l='MpServer', x=63.10, y=100.00, z=66.66], EntityCow['Cow'/92, l='MpServer', x=53.50, y=100.00, z=68.50], EntityCreeper['Creeper'/46429, l='MpServer', x=46.50, y=95.00, z=-37.50], EntityZombie['Zombie'/46947, l='MpServer', x=-44.17, y=95.00, z=39.64], EntitySpider['Spider'/46948, l='MpServer', x=-38.50, y=95.00, z=43.50], EntityChicken['Chicken'/101, l='MpServer', x=74.42, y=58.00, z=60.27], EntitySkeleton['Skeleton'/46439, l='MpServer', x=63.50, y=75.00, z=-9.50], EntityZombie['Zombie'/42346, l='MpServer', x=1.50, y=79.00, z=62.50], EntitySkeleton['Skeleton'/44909, l='MpServer', x=24.50, y=73.00, z=-65.50], EntityCreeper['Creeper'/46707, l='MpServer', x=51.50, y=95.00, z=-59.50], EntitySpider['Spider'/46198, l='MpServer', x=53.50, y=106.00, z=50.50], EntityItem['item.item.dyePowder.black'/45695, l='MpServer', x=36.49, y=58.50, z=12.43], EntitySkeleton['Skeleton'/37521, l='MpServer', x=-29.50, y=83.00, z=-42.50], EntityCreeper['Creeper'/46482, l='MpServer', x=58.50, y=95.00, z=-64.50], EntityZombie['Zombie'/37523, l='MpServer', x=-29.50, y=83.00, z=-43.50], EntityHat['unknown'/155, l='MpServer', x=8.50, y=65.00, z=8.50], EntityHat['unknown'/156, l='MpServer', x=-69.17, y=100.00, z=-67.45], EntityHat['unknown'/157, l='MpServer', x=-65.48, y=93.50, z=33.13], EntityHat['unknown'/158, l='MpServer', x=-64.50, y=100.00, z=38.50], EntityHat['unknown'/159, l='MpServer', x=-52.80, y=58.00, z=-69.20], EntityHat['unknown'/160, l='MpServer', x=-60.50, y=83.00, z=-64.50], EntityHat['unknown'/161, l='MpServer', x=-61.50, y=100.00, z=31.45], EntityHat['unknown'/162, l='MpServer', x=-63.50, y=100.00, z=41.50], EntityHat['unknown'/163, l='MpServer', x=-61.50, y=100.00, z=32.57], EntityHat['unknown'/164, l='MpServer', x=-51.61, y=95.00, z=60.66], EntityItem['item.item.egg'/30884, l='MpServer', x=55.63, y=76.50, z=26.60], EntityHat['unknown'/165, l='MpServer', x=-40.50, y=58.00, z=-88.50], EntityHat['unknown'/166, l='MpServer', x=-37.50, y=89.00, z=-45.50], EntityHat['unknown'/167, l='MpServer', x=-38.55, y=93.50, z=-24.55], EntityHat['unknown'/168, l='MpServer', x=-42.80, y=93.50, z=26.80], EntityHat['unknown'/169, l='MpServer', x=-33.50, y=95.00, z=45.50], EntityHat['unknown'/170, l='MpServer', x=-44.17, y=95.00, z=39.64], EntityHat['unknown'/171, l='MpServer', x=-38.50, y=95.00, z=43.50], EntityHat['unknown'/172, l='MpServer', x=-45.27, y=97.00, z=51.48], EntityHat['unknown'/173, l='MpServer', x=-40.50, y=99.00, z=55.50], EntityHat['unknown'/174, l='MpServer', x=-40.50, y=99.00, z=54.50], EntityHat['unknown'/175, l='MpServer', x=-37.50, y=99.00, z=57.50], EntityHat['unknown'/176, l='MpServer', x=-29.50, y=83.00, z=-42.50], EntityHat['unknown'/177, l='MpServer', x=-29.50, y=83.00, z=-43.50], EntityHat['unknown'/178, l='MpServer', x=-22.80, y=93.00, z=54.20], EntityHat['unknown'/181, l='MpServer', x=-10.28, y=82.00, z=-87.47], EntityHat['unknown'/182, l='MpServer', x=-0.50, y=70.00, z=69.50], EntityCreeper['Creeper'/44215, l='MpServer', x=54.50, y=141.00, z=-45.50], EntitySkeleton['Skeleton'/47040, l='MpServer', x=14.50, y=75.00, z=63.50], EntitySkeleton['Skeleton'/47041, l='MpServer', x=13.50, y=75.00, z=64.50], EntitySkeleton['Skeleton'/47042, l='MpServer', x=12.50, y=75.00, z=63.50], EntityZombie['Zombie'/47043, l='MpServer', x=11.50, y=75.00, z=61.50], EntitySpider['Spider'/43208, l='MpServer', x=-60.50, y=83.00, z=-64.50], EntityHat['unknown'/208, l='MpServer', x=1.50, y=79.00, z=62.50], EntityHat['unknown'/209, l='MpServer', x=14.50, y=75.00, z=63.50], EntityHat['unknown'/210, l='MpServer', x=12.50, y=75.00, z=63.50], EntityHat['unknown'/211, l='MpServer', x=11.50, y=75.00, z=61.50], EntityHat['unknown'/212, l='MpServer', x=13.50, y=75.00, z=64.50], EntityHat['unknown'/213, l='MpServer', x=24.50, y=73.00, z=-65.50], EntityHat['unknown'/214, l='MpServer', x=31.74, y=57.00, z=28.52], EntityHat['unknown'/215, l='MpServer', x=29.73, y=57.00, z=30.52], EntityHat['unknown'/216, l='MpServer', x=38.50, y=95.00, z=-39.50], EntityHat['unknown'/217, l='MpServer', x=46.50, y=95.00, z=-37.50], EntityHat['unknown'/218, l='MpServer', x=39.55, y=93.50, z=-25.55], EntityZombie['Zombie'/37595, l='MpServer', x=63.50, y=80.00, z=36.50], EntityHat['unknown'/219, l='MpServer', x=41.50, y=95.00, z=37.50], EntityHat['unknown'/220, l='MpServer', x=43.45, y=60.60, z=65.42], EntityHat['unknown'/221, l='MpServer', x=58.50, y=95.00, z=-64.50], EntityHat['unknown'/222, l='MpServer', x=51.50, y=95.00, z=-59.50], EntityHat['unknown'/223, l='MpServer', x=54.50, y=141.00, z=-45.50], EntityHat['unknown'/224, l='MpServer', x=61.50, y=75.00, z=-9.50], EntityHat['unknown'/225, l='MpServer', x=63.50, y=75.00, z=-11.50], EntityHat['unknown'/226, l='MpServer', x=62.50, y=75.00, z=-9.50], EntityHat['unknown'/227, l='MpServer', x=63.50, y=75.00, z=-9.50], EntityHat['unknown'/228, l='MpServer', x=61.50, y=79.00, z=4.50], EntityHat['unknown'/229, l='MpServer', x=59.08, y=79.00, z=24.50], EntityHat['unknown'/230, l='MpServer', x=63.50, y=80.00, z=36.50], EntitySkeleton['Skeleton'/45544, l='MpServer', x=-51.61, y=95.00, z=60.66], EntitySpider['Spider'/41449, l='MpServer', x=64.50, y=79.00, z=-0.50], EntityHat['unknown'/238, l='MpServer', x=53.50, y=106.00, z=50.50], EntityCreeper['Creeper'/46831, l='MpServer', x=61.50, y=75.00, z=-9.50], EntityHat['unknown'/239, l='MpServer', x=63.10, y=100.00, z=66.66], EntityCreeper['Creeper'/46832, l='MpServer', x=65.50, y=75.00, z=-7.50], EntityHat['unknown'/240, l='MpServer', x=53.50, y=100.00, z=68.50], EntitySpider['Spider'/46833, l='MpServer', x=63.50, y=75.00, z=-11.50], EntityHat['unknown'/241, l='MpServer', x=65.50, y=75.00, z=-7.50], EntityHat['unknown'/242, l='MpServer', x=64.50, y=79.00, z=-0.50], EntityHat['unknown'/243, l='MpServer', x=74.42, y=58.00, z=60.27], EntityHat['unknown'/244, l='MpServer', x=64.47, y=84.00, z=69.21], EntityZombie['Zombie'/47099, l='MpServer', x=-0.50, y=70.00, z=69.50], EntitySkeleton['Skeleton'/46845, l='MpServer', x=31.74, y=57.00, z=28.52], EntitySkeleton['Skeleton'/46846, l='MpServer', x=29.73, y=57.00, z=30.52]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 895992232 bytes (854 MB) / 4439670784 bytes (4234 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 84 mods loaded, 84 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version               | Source                                             | Signature                                |
	|:------ |:--------------------- |:--------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                   | 9.42                  | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                   | 8.0.99.99             | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2854          | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy     | 1.0.0                 | minecraft.jar                                      | None                                     |
	| LCHIJA | obfuscate             | 0.4.2                 | minecraft.jar                                      | None                                     |
	| LCHIJA | securitycraft         | v1.8.17               | [1.12.2] SecurityCraft v1.8.17.jar                 | None                                     |
	| LCHIJA | actuallyadditions     | 1.12.2-r151           | ActuallyAdditions-1.12.2-r151-2.jar                | None                                     |
	| LCHIJA | biomesoplenty         | 7.0.1.2441            | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar      | None                                     |
	| LCHIJA | craftstudioapi        | 1.0.0                 | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCHIJA | harvestcraft          | 1.12.2zb              | Pam's HarvestCraft 1.12.2zg.jar                    | None                                     |
	| LCHIJA | animania              | 1.7.3                 | animania-1.12.2-1.7.3.jar                          | None                                     |
	| LCHIJA | applecore             | 3.2.0                 | AppleCore-mc1.12.2-3.2.0.jar                       | None                                     |
	| LCHIJA | aquaculture           | 1.6.8                 | Aquaculture-1.12.2-1.6.8.jar                       | None                                     |
	| LCHIJA | crafttweaker          | 4.1.20                | CraftTweaker2-1.12-4.1.20.562.jar                  | None                                     |
	| LCHIJA | mtlib                 | 3.0.6                 | MTLib-3.0.6.jar                                    | None                                     |
	| LCHIJA | modtweaker            | 4.0.18                | modtweaker-4.0.18.jar                              | None                                     |
	| LCHIJA | jei                   | 4.15.0.291            | jei_1.12.2-4.15.0.291.jar                          | None                                     |
	| LCHIJA | tombstone             | 3.7.3                 | tombstone-3.7.3-1.12.2.jar                         | None                                     |
	| LCHIJA | quark                 | r1.6-179              | Quark-r1.6-179.jar                                 | None                                     |
	| LCHIJA | autoreglib            | 1.3-32                | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCHIJA | buildinggadgets       | 2.8.3                 | BuildingGadgets-2.8.3.jar                          | None                                     |
	| LCHIJA | camera                | 1.0.9                 | camera-1.0.9.jar                                   | None                                     |
	| LCHIJA | ctm                   | MC1.12.2-1.0.2.31     | CTM-MC1.12.2-1.0.2.31.jar                          | None                                     |
	| LCHIJA | chisel                | MC1.12.2-1.0.2.45     | Chisel-MC1.12.2-1.0.2.45.jar                       | None                                     |
	| LCHIJA | chiselsandbits        | 14.33                 | chiselsandbits-14.33.jar                           | None                                     |
	| LCHIJA | comforts              | 1.4.1.3               | comforts-1.12.2-1.4.1.3.jar                        | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | cookingforblockheads  | 6.5.0                 | CookingForBlockheads_1.12.2-6.5.0.jar              | None                                     |
	| LCHIJA | cosmeticarmorreworked | 1.12.2-v5a            | CosmeticArmorReworked-1.12.2-v5a.jar               | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | ctgui                 | 1.0.0                 | CraftTweaker2-1.12-4.1.20.562.jar                  | None                                     |
	| LCHIJA | crafttweakerjei       | 2.0.3                 | CraftTweaker2-1.12-4.1.20.562.jar                  | None                                     |
	| LCHIJA | opframe               | 1.4.0                 | OnlinePicFrame_v1.4.38_mc1.12.2.jar                | None                                     |
	| LCHIJA | playerrevive          | 1.0                   | PlayerRevive_v1.2.34_mc1.12.2.jar                  | None                                     |
	| LCHIJA | creativecore          | 1.10.0                | CreativeCore_v1.10.13_mc1.12.2.jar                 | None                                     |
	| LCHIJA | modcurrency           | 1.12-1.3.11           | Currency-1.12.0-1.3.11.jar                         | None                                     |
	| LCHIJA | customnpcs            | 1.12                  | CustomNPCs_1.12.2-(01Oct19).jar                    | None                                     |
	| LCHIJA | cxlibrary             | 1.6.1                 | cxlibrary-1.12.1-1.6.1.jar                         | None                                     |
	| LCHIJA | ptrmodellib           | 1.0.4                 | PTRLib-1.0.4.jar                                   | None                                     |
	| LCHIJA | props                 | 2.6.3                 | Decocraft-2.6.3_1.12.2.jar                         | None                                     |
	| LCHIJA | df-roads              | 1.5.2-mc1.12.2        | df-roads-1.5.2-mc1.12.2.jar                        | None                                     |
	| LCHIJA | ding                  | 1.0.2                 | Ding-1.12.2-1.0.2.jar                              | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | doubleslabs           | 0.4.2                 | DoubleSlabs-1.12-0.4.2.jar                         | 8fe188525792c6c578d0914522e8913ba4334a41 |
	| LCHIJA | sereneseasons         | 1.2.18                | SereneSeasons-1.12.2-1.2.18-universal.jar          | None                                     |
	| LCHIJA | orelib                | 3.6.0.1               | OreLib-1.12.2-3.6.0.1.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround             | 3.6.1.0               | DynamicSurroundings-1.12.2-3.6.1.0.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | elevatorid            | 1.3.14                | ElevatorMod-1.12.2-1.3.14.jar                      | None                                     |
	| LCHIJA | exoticbirds           | 1.0                   | Exotic Birds 1.12.2-3.1.0.jar                      | None                                     |
	| LCHIJA | extrautils2           | 1.0                   | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LCHIJA | falling_tree          | 2.1.0                 | FallingTree-1.12.2-2.1.0+25.jar                    | None                                     |
	| LCHIJA | fasterladderclimbing  | 0.1-146               | FasterLadderClimbing-1.12-0.1-146.jar              | None                                     |
	| LCHIJA | fastleafdecay         | v14                   | FastLeafDecay-v14.jar                              | None                                     |
	| LCHIJA | foamflower            | 1.12.2-1.0.0.0-beta1  | foamflower-1.12.2-1.0.0.0-beta1.jar                | None                                     |
	| LCHIJA | forgivingvoid         | 1.1.0                 | ForgivingVoid_1.12.2-1.1.0.jar                     | None                                     |
	| LCHIJA | cfm                   | 6.3.1                 | furniture-6.3.1-1.12.2.jar                         | None                                     |
	| LCHIJA | guideapi              | 1.12-2.1.8-63         | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
	| LCHIJA | ichunutil             | 7.2.2                 | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | hats                  | 7.1.0                 | Hats-1.12.2-7.1.0.jar                              | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | waila                 | 1.8.26                | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCHIJA | lunatriuscore         | 1.2.0.42              | LunatriusCore-1.12.2-1.2.0.42-universal.jar        | None                                     |
	| LCHIJA | ingameinfoxml         | 2.8.2.94              | InGameInfoXML-1.12.2-2.8.2.94-universal.jar        | None                                     |
	| LCHIJA | igisereneseasons      | 1.0.0.1               | igisereneseasons-1.0.0.1.jar                       | None                                     |
	| LCHIJA | ironbackpacks         | 1.12.2-3.0.8-12       | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
	| LCHIJA | ironchest             | 1.12.2-7.0.67.844     | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| LCHIJA | journeymap            | 1.12.2-5.7.1          | journeymap-1.12.2-5.7.1.jar                        | None                                     |
	| LCHIJA | jeresources           | 0.9.2.60              | JustEnoughResources-1.12.2-0.9.2.60.jar            | None                                     |
	| LCHIJA | malisiscore           | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                       | None                                     |
	| LCHIJA | malisisdoors          | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
	| LCHIJA | mc_donalds_thingy     | 1.0.0                 | Mcdonald's Mod.jar                                 | None                                     |
	| LCHIJA | mobdismemberment      | 7.0.0                 | MobDismemberment-1.12.2-7.0.0.jar                  | None                                     |
	| LCHIJA | morefurnaces          | 1.10.5                | MoreFurnaces-1.12.2-1.10.6.jar                     | None                                     |
	| LCHIJA | llibrary              | 1.7.19                | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | mowziesmobs           | 1.5.4                 | mowziesmobs-1.5.4.jar                              | None                                     |
	| LCHIJA | potioncore            | 1.9_for_1.12.2        | PotionCore-1.9_for_1.12.2.jar                      | None                                     |
	| LCHIJA | qualitytools          | 1.0.7_for_1.12.2      | QualityTools-1.0.7_for_1.12.2.jar                  | None                                     |
	| LCHIJA | roguelike             | 1.8.0                 | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
	| LCHIJA | rustic                | 1.1.3                 | rustic-1.1.3.jar                                   | None                                     |
	| LCHIJA | spartanshields        | 1.5.4                 | SpartanShields-1.12.2-1.5.4.jar                    | None                                     |
	| LCHIJA | torchmaster           | 1.8.1.81              | torchmaster_1.12.2-1.8.1.81.jar                    | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| LCHIJA | vehicle               | 0.43.5                | vehicle-mod-0.43.5-1.12.2.jar                      | None                                     |
	| LCHIJA | vending               | 1.12.2-3.0.1.2        | vending-1.12.2-3.0.1.2.jar                         | None                                     |
	| LCHIJA | gvc                   | 1.2.0                 | Voice Chat Reloaded-1.2.0.jar                      | None                                     |
	| LCHIJA | wailaharvestability   | 1.1.12                | WailaHarvestability-mc1.12-1.1.12.jar              | None                                     |
	| LCHIJA | wawla                 | 2.6.275               | Wawla-1.12.2-2.6.275.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | betteranimalsplus     | 9.0.1                 | betteranimalsplus-1.12.2-9.0.1.jar                 | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
CreativePatchingLoader (CreativeCore_v1.10.13_mc1.12.2.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 445.87' Renderer: 'GeForce RTX 2080 Ti/PCIe/SSE2'
	Launched Version: forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce RTX 2080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 24x AMD Ryzen 9 3900X 12-Core Processor

**Comment by Tschipp** [comment] 2020-05-28 07:26
Dupe of Thermal Expansion crash, fixed in dev.
But either way, why are you joining vanilla servers with mods?

**Closed as completed** 2020-05-28 07:26 UTC
Labels: bug, duplicate, 1.12, crash

**Comment by SheroxGG** [comment] 2020-05-28 14:15
I dont have Thermal Expansion. If I remove the mod from the modpack I can join the server. I am joining a lobby with mods because from there Ill join the modded server. Without animania I can do it, with animania I cant.
