### ISSUE TITLE
Not all animal models spawning

### ISSUE THREAD

**Issue by FinleyOderSo** [capnkirok/animaniamod#314] opened 2019-05-05 19:05 UTC
I really want to play with this mod but only the "standard models" spawn naturally.
For example only the pink model of the pig is spawning in my world naturally. Or only the white sheep model. When I try to spawn animals with the normal Minecraft spawn eggs sometimes I only hear the sound of the animal when it spawns but there actually isn't any animal spawning. And sometimes the animal is spawning but then it's again only the "standard model". The spawn eggs that come with the mod work tho.

I'm playing in single player on 1.12.2.

**Comment by MizuNomy** [comment] 2019-06-17 00:39
Hello, is there any more mods you have installed or just purely Animania? Did you install Craftstudio API?

**Comment by capnkirok** [comment] 2019-08-20 00:02
@FinleyOderSo was this a new world or an existing world?

**Comment by capnkirok** [comment] 2019-08-25 22:11
Closing this one. Numerous test show spawning is working as intended.

**Closed as completed by capnkirok** 2019-08-25 22:11 UTC
Labels: 1.12, Can't Reproduce 🤔
